source 'https://rubygems.org'

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '1.16.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'